name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

#      - name: Run PHP CS Fixer
#        run: vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no

#      - name: Run PHPStan
#        run: vendor/bin/phpstan analyze -c phpstan.neon

      - name: Execute tests
        run: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover
